### ISSUE TITLE
Multi Select Broken

### ISSUE THREAD

**Issue by aribornstein** [Microsoft/VoTT#342] opened 2018-12-04 21:36 UTC
The multi select feature only tags one bounding box in the latest build @kichinsky

**Comment by aribornstein** [comment] 2018-12-04 21:37
Also when selecting a tag the bounding box freezes and i loose all the colors

![image](https://user-images.githubusercontent.com/3045407/49474513-8b52ce80-f81d-11e8-9cbf-5e5e4175f79f.png)

**Comment by aribornstein** [comment] 2018-12-04 21:40
Also seeing really weird behaivor 

![image](https://user-images.githubusercontent.com/3045407/49474652-e4bafd80-f81d-11e8-84a8-476f65bf97f1.png)

**Comment by kichinsky** [comment] 2018-12-04 22:40
@aribornstein I have seen that weird behavior, but can't reproduce it in my lasest update. Maybe I occasionally changed something. Can you check the #341?

On multi-select -- I think we do not support that yet, but I will check. We have to figure out some logic with tags overlapping for multi-selection. 

Related #248

**Comment by aribornstein** [comment] 2018-12-05 07:44
Will do with overlapping tags one idea is to provide priority to the tag with the smallest surface area.

**Comment by wbreza** [comment] 2019-04-15 05:03
Resolved in v2.0.0

**Closed by wbreza** 2019-04-15 05:03 UTC
Labels: feature
