### ISSUE TITLE
TensorFlowPascalVoc Export is generating wrong value of ymax

### ISSUE THREAD

**Issue by kurmanadhvalla** [Microsoft/VoTT#766] opened 2019-04-16 10:31 UTC
In generated xml files , ymax in bounding box info is wrongly generated.  

It is because in  src\providers\export\tensorFlowPascalVOC\tensorFlowPascalVOCTemplates.ts 

In object template ymax is wongly defined as xmin instead of ymax

**Comment by wbreza** [comment] 2019-04-16 14:49
Duplicate of #760. Closing

**Closed by wbreza** 2019-04-16 14:49 UTC
