### ISSUE TITLE
V2 Preview - Hovering on a notification pauses the status bar

### ISSUE THREAD

**Issue by arode** [Microsoft/VoTT#582] opened 2019-02-14 23:31 UTC
**Describe the bug**
While an action is being performed, such as saving or exporting, if my mouse is on the notification flyout the status bar stops.

**To Reproduce**
1. Tag images
2. Save project
3. Export project, move mouse to notification

**Expected behavior**
Notification still acts as if the mouse wasn't on it (countdown continues)

**Screenshots**

**Platform**
[X] Electron
[ ] Browser

**OS**
[X] Windows
[ ] Mac
[ ] Linux

**Comment by wbreza** [comment] 2019-04-02 15:40
This is by design to enable the user extended opportunity to read the toast message if desired.  You can optionally click the "X" to close it out.

**Closed by wbreza** 2019-04-02 15:40 UTC
Labels: question
